apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ssh-bastion
  name: ssh-bastion
  namespace: ssh-bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ssh-bastion
  template:
    metadata:
      labels:
        run: ssh-bastion
    spec:
      serviceAccountName: "ssh-bastion"
      containers:
      - image: quay.io/eparis/ssh:latest
        imagePullPolicy: Always
        name: ssh-bastion
        ports:
        - containerPort: 22
          name: ssh
          protocol: TCP
        volumeMounts:
        - name: ssh-host-keys
          mountPath: "/etc/ssh/"
          readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: ssh-host-keys
        secret:
          secretName: ssh-host-keys
          items:
          - key: ssh_host_rsa_key
            path: ssh_host_rsa_key
            mode: 256
          - key: ssh_host_ecdsa_key
            path: ssh_host_ecdsa_key
            mode: 256
          - key: ssh_host_ed25519_key
            path: ssh_host_ed25519_key
            mode: 256
          - key: sshd_config
            path: sshd_config
      restartPolicy: Always
