apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    openshift.io/description: Allows ssh-pod to run as root
  name: ssh-bastion
  namespace: ssh-bastion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ssh-bastion
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:ssh-bastion:ssh-bastion
