apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ssh-bastion
  namespace: ssh-bastion
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
